//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public interface InventoryItem {
	public bool isRotate = false;
	public int sizex;
	public int sizey;

	public int stackCount;
	public int maxStackCount;

	public double weight;
}
