//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class TetrisInventoryItem{
	public InventoryItem item;
	public Vector2 position;

	public TetrisInventoryItem (InventoryItem item, Vector2 position){
		this.item = item;
		this.position = position;
	}

	public TetrisInventoryItem () {}
}

